name: Build and Test Frontend
on:
  workflow_call:

jobs:
  build:
    name: "Build and Test"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Node.js and install dependencies
        uses: ./.github/actions/setup

#      - name: Lint code
#        working-directory: ./frontend
#        run: pnpm biome

      - name: Type check
        working-directory: ./frontend
        run: pnpm exec tsc --noEmit

      - name: Run tests
        working-directory: ./frontend
        run: pnpm test

      - name: Build for production
        working-directory: ./frontend
        run: pnpm build
