name: Build and Test on Main

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml
    permissions:
      packages: read
      contents: read
      id-token: write

  build-and-push-image:
    needs: build-and-test
    name: "Build and Push Docker Image"
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Build and push Docker image to GAR
        uses: nais/docker-build-push@423a915c9b72edf2ba848b88171ccb0489e2a40a # v0
        id: docker-build-push
        with:
          team: infotek
          docker_context: ./frontend

  deploy-dev:
    needs: build-and-push-image
    name: "Deploy Frontend to dev-gcp"
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Deploy frontend to dev-gcp
        uses: nais/deploy/actions/deploy@1de80da70ad26556ecdc5964a8b7ec3bbed98120 # v2
        env:
          CLUSTER: dev-gcp
          TEAM: infotek
          RESOURCE: .nais/app/frontend.yaml
          VARS: .nais/dev.json
          IMAGE: ${{ needs.build-and-push-image.outputs.image }}
