name: Build and Test on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml
    permissions:
      contents: read
      packages: read
